rango/urls.py
from django.conf.urls import include
from django.http import request
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
path('', views.index, name='index'),
path('about/', views.about, name='about'),
path("category/<slug:category_name_slug>/subcategory/<slug:subcategory_name_slug>/", views.show_subcategory, name="show_subcategory"),
path("category/<slug:category_name_slug>/", views.show_category, name="show_category"),
path("category/<slug:category_name_slug>/subcategory/<slug:subcategory_name_slug>/page/<slug:page_name_slug>/", views.show_page, name="show_page"),
path("add_category/", views.add_category, name="add_category"),
path("category/<slug:category_name_slug>/subcategory/<slug:subcategory_name_slug>/", views.show_subcategory, name="show_subcategory"),
path("category/<slug:category_name_slug>/add_subcategory/", views.add_subcategory, name="add_subcategory"),
path("category/<slug:category_name_slug>/subcategory/<slug:subcategory_name_slug>/add_page/", views.add_page, name="add_page"),
path("<slug:page_name_slug>/add_review/",views.add_Review, name="add_review"),
path('profile/', views.profile, name='profile'),
path("accounts/register/", views.register, name="register"),
path("accounts/login/", views.user_login, name="login"),
path("accounts/logout/", views.user_logout, name="logout"),
path("accounts/password/change", views.change_password, name="change_password"),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
path('', views.index, name='index'),
path('rango/', include('rango.urls')),
path('admin/', admin.site.urls),
path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import fields
from rango.models import LikedPage, Page, Category, UserProfile, Review, Subcategory

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to privde additional information on the form.
    class Meta:
        #Provide and associated between the ModelForm and a model
        model=Category
        fields=("name",)

class SubcategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Subcategory.NAME_MAX_LENGTH, help_text="Please enter the subcategory name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to privde additional information on the form.
    class Meta:
        #Provide and associated between the ModelForm and a model
        model=Subcategory
        fields=("name",)

class PageForm(forms.ModelForm):
    ##CHOICES =[('1','*'),('2','**'),('3','***'),('4','****'),('5','*****')]
    name = forms.CharField(max_length=Page.NAME_MAX_LENGTH, help_text="Please enter the title of the page.")
    url=forms.URLField(max_length=Page.URL_MAX_LENGTH, help_text="Please enter the URL of the page.")
    views=forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        #Provide and association between the ModelForma and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we dont need every field in the model present.
        # Some fields may allow NULl values; we may not want to include them
        # Here, we are hiding the foreign key
        # We can either exclude the category field from the form
        fields=("name","url","views")
       # exclude = ("subcategory","views","slug", "user", "avg_rating")
        # or specify the fields to inlcude and don't include the category field - fields = ("title", "url", "views")

        def clean(self):
            cleaned_data = self.cleaned_data
            url = cleaned_data.get("url")

            #if url is not empty and doesn't start with "http://", prepend with it
            if url and not url.startswith("http://"):
                url = f"http://{url}"
                cleaned_data["url"] = url
            
            return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "email", "password",)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("website", "picture")


class ReviewForm(forms.ModelForm):

    rating = forms.IntegerField(help_text="Rate this page: ")
    title = forms.CharField(max_length=Review.BriefDescription_Max_Length, help_text='Give your review a title: ')
    text= forms.CharField(max_length=Review.ReviewText_Max_Length, help_text='Review: ')
    def clean(self):
        cleaned_data = super().clean()
        rating = cleaned_data.get('rating')
        if rating>5 or rating<0:
            raise ValidationError("rating must be between 1 and 5")


    class Meta :
        model= Review
        fields = ("rating","title","text")
        
class URLForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("website",)

class PictureForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("picture",)
class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ("password", "password")

rango/views.py
from django.db.models.aggregates import Avg
from rango.models import Category, Page, Subcategory, UserProfile, LikedPage, Review
from django.urls import reverse
from django.http.response import HttpResponse
from rango.forms import CategoryForm, PageForm, SubcategoryForm, UserProfileForm, UserForm, PasswordChangeForm, URLForm, PictureForm, ReviewForm
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from datetime import datetime


def index(request):

    rating_page_list1 = Page.objects.order_by("-avg_rating")[:3]
    rating_page_list2 = Page.objects.order_by("-avg_rating")[3:6]
    page_list1 = Page.objects.order_by("-views")[:3]
    page_list2 = Page.objects.order_by("-views")[3:6]
    review_list1 = Review.objects.order_by("-datetime")[:3]
    review_list2 = Review.objects.order_by("-datetime")[3:6]

    context_dict = {}
    context_dict["reviews1"] = review_list1
    context_dict["reviews2"] = review_list2
    context_dict["page_ratings1"] = rating_page_list1
    context_dict["page_ratings2"] = rating_page_list2
    context_dict["pages1"] = page_list1
    context_dict["pages2"] = page_list2

    visitor_cookie_handler(request)
    response = render(request, "rango/index.html", context=context_dict)

    return response

def about(request):
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict["visits"] = request.session["visits"]
    
    return render(request, 'rango/about.html', context=context_dict)



def show_category(request, category_name_slug):

    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        subcategories = Subcategory.objects.filter(category=category)
        context_dict["subcategories"] = subcategories
        context_dict["category"] = category
    except Category.DoesNotExist:
            context_dict["category"] = None
            context_dict["subcategories"] = None

    return render(request, "rango/category.html", context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()
    # HTTP POST?
    if request.method == "POST":
        form = CategoryForm(request.POST)

        if form.is_valid():

            category = form.save(commit=False)
            category.user = request.user
            category.save()

            return redirect("/rango/")


    return render(request, "rango/add_category.html", {"form": form})

def show_subcategory(request, category_name_slug, subcategory_name_slug):

    context_dict = {}

    try:

        category = Category.objects.get(slug=category_name_slug)


        subcategories = Subcategory.objects.filter(category=category)

        subcategory = subcategories.get(slug=subcategory_name_slug)
     
        pages = Page.objects.filter(subcategory=subcategory)

        context_dict['category'] = category
        context_dict["subcategory"] = subcategory
        context_dict["pages"] = pages

    except Subcategory.DoesNotExist:

            context_dict["subcategory"] = None
            context_dict["pages"] = None

    return render(request, "rango/subcategory.html", context=context_dict)


@login_required
def add_subcategory(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    if category is None:
        return redirect("/rango/")

    
    form = SubcategoryForm()

    if request.method == "POST":
        form = SubcategoryForm(request.POST)

        if form.is_valid():
            if category:
                subcategory = form.save(commit=False)
                subcategory.category = category
                subcategory.views = 0
                subcategory.user = request.user
                subcategory.save()
                return redirect(reverse("rango:show_category", kwargs={"category_name_slug": category_name_slug}))

        else:
            print(form.errors)

    context_dict = {"form": form, "category": category}
    return render(request, "rango/add_subcategory.html", context=context_dict)



def show_page(request, page_name_slug, category_name_slug, subcategory_name_slug):

    context_dict ={}
    userNotReviewed = True

    ## GET PAGE
    try:
        page=Page.objects.get(slug=page_name_slug)
        page.views += 1
        page.save()
    except Page.DoesNotExist:
        return HttpResponse("Page does not exist")

    ## GET ALL REVIEWS FOR THIS PAGE AND THE COUNT OF REVIEWS FOR THIS PAGE.
    try:
        page_reviews = Review.objects.filter(page=page)
        page_reviews_count = Review.objects.filter(page=page).count() 
    except Review.DoesNotExist:
        page_reviews = None
        page_reviews_count=0


    ## FIND OUT IF CURRENT USER HAS REVIEWED THIS PAGE
    for review in page_reviews:
      if review.user == request.user:
          userNotReviewed=False
    
    ## determine if user has liked the page
    
    if request.user.is_authenticated and LikedPage.objects.filter(user=request.user, page=page).exists():
        like_status = True
    else:
        like_status = False


    context_dict ["userNotReviewed"]=userNotReviewed
    context_dict ["form"]=ReviewForm()
    context_dict["page"] = page
    context_dict["Reviews"]=page_reviews
    context_dict["like_status"]=like_status
    context_dict["page_reviews_count"]= page_reviews_count

    if request.method == "POST":

        # handle unlike page post requests
        if 'unlike' in request.POST:
            LikedPage.objects.filter(user=request.user, page=page).delete()
            return redirect(reverse("rango:show_page", kwargs={"category_name_slug": category_name_slug,
                                                            "subcategory_name_slug": subcategory_name_slug,
                                                           "page_name_slug": page_name_slug}))
        # handle like page post requests
        elif 'like' in request.POST:
            LikedPage.objects.get_or_create(user=request.user, page=page)[0].save()
            return redirect(reverse("rango:show_page", kwargs={"category_name_slug": category_name_slug,
                                                            "subcategory_name_slug": subcategory_name_slug,
                                                            "page_name_slug": page_name_slug}))

    return render (request, "rango/page.html", context_dict)

#called form the page template, this method processes a form that the user has submitted.
#it calls the show_page view in order to redirect the user to the same page and therefore "refresh" it, showing the changer he or she has made.
def add_Review (request,page_name_slug):
    
    page= Page.objects.get(slug=page_name_slug)
    
    form=ReviewForm(request.POST)
    if form.is_valid():
        review = form.save(commit=False)
        review.page=page
        review.user=request.user
        review.save()

        ## Set page average Rating
        numReviews = Review.objects.filter(page=page).count()
        currentTotal = page.avg_rating * (numReviews-1)
        newTotal = currentTotal + int(form.data["rating"])
        newAverage = round(newTotal / numReviews, 2)

        page.avg_rating = newAverage
        page.save()




    
    return show_page(request, page_name_slug, page.subcategory.category.slug, page.subcategory.slug)





@login_required
def add_page(request, category_name_slug, subcategory_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
        subcategory = Subcategory.objects.get(slug=subcategory_name_slug)
    except Category.DoesNotExist:
        category = None
        subcategory = None

    if category is None or subcategory is None:
        return redirect("/rango/")

    form = PageForm()

    if request.method == "POST":
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.subcategory = subcategory
                page.views = 0
                page.user = request.user
                page.save()

                return redirect(reverse("rango:show_subcategory", kwargs={"category_name_slug": category_name_slug,
                                                                        "subcategory_name_slug": subcategory_name_slug}))


    context_dict = {"form": form, "category": category, "subcategory": subcategory}
    return render(request, "rango/add_page.html", context=context_dict)

def visitor_cookie_handler(request):
    
    visits = int(get_server_side_cookie(request, "visits", "1"))
    last_visit_cookie = get_server_side_cookie(request, "last_visit", str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], "%Y-%m-%d %H:%M:%S")

    if(datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session["last_visit"] = str(datetime.now())
    else:
        request.session["last_visit"] = last_visit_cookie

    request.session["visits"] = visits

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


##display the users profile
@login_required
def profile(request):

    # get logged on user
    user_profile = UserProfile.objects.get_or_create(user=request.user)[0]

    # get all objects belonging to user
    categories = Category.objects.filter(user=request.user)
    subcategories = Subcategory.objects.filter(user=request.user)
    reviews = Review.objects.filter(user=request.user)
    liked_pages = LikedPage.objects.filter(user=request.user)

    context_dict = {}

    context_dict["user_profile"] = user_profile

    url_form = URLForm()
    pic_form = PictureForm()

    context_dict["URLForm"] = url_form

templates/rango/add_category.html
{% extends 'rango/base.html' %} 
{% load staticfiles %}


{% block title_block %}
    Add a Category
{% endblock %}
{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Add a Category</h1>
        </div>
    </div>

    <div>
        <form id="category_form" method = "post" action="{% url 'rango:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{hidden}}
            {% endfor %} 
            {% for field in form.visible_fields%} 
                {{field.errors}}
                {{field.help_text}}
                {{field}}

            {%endfor%} 
            <input type="submit" name="submit" value="Create Category" />
        </form>
    </div>
    
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Page</h1>
    </div>
</div>
<div>
    
    <form id="page_form" method = "post" action="{% url 'rango:add_page' category.slug subcategory.slug %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{hidden}}
        {% endfor %} 
        {% for field in form.visible_fields%} 
            {{field.errors}}
            {{field.help_text}}
            {{field}}
        {%endfor%} 
        <input type="submit" name="submit" value="Create Page">
    </form>
</div>
{% endblock %}

templates/rango/add_subcategory.html
<!DOCTYPE html>

{% extends 'rango/base.html' %} 
{% load staticfiles %}


{% block title_block %}
    Add a Subcategory
{% endblock %}
{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Add a Subcategory</h1>
        </div>
    </div>

    <div>
        <form id="category_form" method = "post" action="{% url 'rango:add_subcategory' category.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{hidden}}
            {% endfor %} 
            {% for field in form.visible_fields%} 
                {{field.errors}}
                {{field.help_text}}
                {{field}}

            {%endfor%} 
            <input type="submit" name="submit" value="Create Subcategory" />
        </form>
    </div>
    
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
    <head>
        
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   
    <!-- jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Bootstrap Javascript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <title>
        SourceRank - {% block title_block %}{% endblock %}
    </title>

    <!-- jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Bootstrap Javascript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    
    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">

    {% block head_block %}{% endblock %}
    </head>
    
    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-2" id="navbar">
                <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' %}">Profile</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:logout' %}?next=/rango/">Logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:register' %}">Register Here</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
                <form class="form-inline">
                    <input autocomplete="off" class="form-control mr-sm-2"type="search" placeholder="Search..." aria-label="Search" id="searchBar">
                </form>
            </nav>
        </header>
        
        <div class="container-fluid">
            <div class="row">
                
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>
                
                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">	
                    {% block search_block %}
                        {% get_search_results %}
                    {% endblock %}	
                    {% block body_block %}{% endblock %}
                    
                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                    </footer>
                </main>
            </div>
        </div>

        
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
        <script src="{% static 'search.js' %}"></script>
    </body>
</html>

templates/rango/categories.html
<ul class="nav flex-column">
    <a class="btn btn-primary" href="{% url 'rango:add_category' %}">Add Category</a>
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
                        <span data-feather="archive"></span>{{c.name}}
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
                        <span data-feather="archive"></span>{{ c.name }}
                    </a>
                </li>
            {% endif %}
        {% endfor %}    
    {% else %}
        <li class="nav-item">There are no categories present.</li>
    {% endif %} 
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %} 
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
    <div class="cat-container">
    <div class="jumbotron p-4 cat-header">
        <div class="container">
            <h1 class="jumbotron-heading">{{ category.name }}</h1>
        </div>
    </div>
        {% if subcategories %}
            
            <ul class="category-list list-group">
                {% for subcategory in subcategories %}

                    <li class="list-group-item ">
                        <a class="fa fa-book fa-2x" href="{% url 'rango:show_subcategory' category.slug subcategory.slug %}">
                            <span class="sub-name">{{ subcategory.name }}</span></a>
                    </li>

                {% endfor %}
            </ul> <br />
           
        {% else %} 
            <strong>This category currently contains no subcategories.</strong>
        {% endif %}
        {% if user.is_authenticated %}
            <a class = "btn btn-primary add-cat-button" href="{% url 'rango:add_subcategory' category.slug %}">Add Subcategory</a> <br />     
        {% endif %}
    {% else %}
        The specified category does not exist.
    {% endif %}
    </div>

{% endblock %}

templates/rango/change_password.html
{% extends 'rango/base.html' %}

{% block title %} Change Password {% endblock %}

{% block body_block %}
<h1> Change Password </h1>
{% if success %}
    <p>You have successfully changed your password</p>
{% endif %}

<form id="user_form" method="post" enctype="multipart/form-data" action="{% url 'rango:change_password' %}">
    {% csrf_token %}
    <!-- New Password: <input type="password" name="password" value="" size="50" />
    <br />
    Repeat: <input type="password" name="password1" value="" size="50" />
    <br />
     -->
    {{form.as_p}}
    <input type="submit" name="submit" value="Change Password">
</form>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load socialaccount %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<h1>Login</h1>

{% if invalid %}
    <p>Invalid login details, please try again</p>
{% endif %}

<form id="login_form" method="post" action="{% url 'rango:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" />
    <br />
    <input type="submit" value="submit" />
    <a href="{% provider_login_url 'google' %}">Login with Google</a>
</form>
{% endblock %}

templates/rango/page.html
{%extends 'rango/base.html' %}
{% load staticfiles %}
{%block title_block%}
    {{page.name}}
{%endblock%}
{%block body_block%}
    <div id="page-overview" >
            <div id="page-and-views">
                <h1>{{page.name}}</h1> 
                <div class="views">
                    <svg xmlns="http://www.w3.org/2000/svg" class="mt-2" width="2rem" height="2rem" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                        <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                        <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                      </svg>
                      <h4  class="">{{page.views}}</h4>
                </div>
     
                
            </div>
            <div id="added_by">
                <h4 id="" >Added by: {{page.user.username}}</h4>
            </div>
            <a id="page-url" href="{{page.url}}">{{page.url}}</a>

            <div id = "like-button">
                {% if like_status %}
                <form method = "post" action="{% url 'rango:show_page' page.subcategory.category.slug page.subcategory.slug  page.slug %}">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary" name="unlike" value="Unlike Page" />
                </form>
                {% else %}
                <form method = "post" action="{% url 'rango:show_page' page.subcategory.category.slug page.subcategory.slug  page.slug %}">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary" name="like" value="Like Page" />
                </form>
                
                {% endif %}
            </div>
        
    </div>

    

    

    

    {%if user.is_authenticated %}
    {%if userNotReviewed %}
    <div id="review-div" class="">
    <div id="review-div" >

        <form id="Review_form" class="jumbotron" method="post" action=" {% url 'rango:add_review' page.slug %}">
            <h2>Leave a Review</h2>
                {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                 {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }} 
            {%endfor%}
            <input type="submit" class="btn btn-primary" name="submit" value="Add Review">
            </form>
    </div>
    {%endif%}
    {%endif%}

    

    <div class="review-div" id="review-list">
        <h2> {{page_reviews_count}} Reviews for this page! Average score: <span class= "badge badge-pill badge-primary">{{page.avg_rating}}</span></h1>
        {%if Reviews%}

            {%for review in Reviews%}
    
            <div class="card" id="page-review-card">
                <div class="card-header">
                    <p>{{review.user}}</p>
                    <p>{{review.datetime}}</p>
                </div>
              <div class="card-body">
                <div class="rating cardTitle">
                    <h5 class="card-title">{{review.page.name}}</h5>
                    <p>{{review.rating}}</p>
                </div>
                <strong class="card-text"><p class="card-text">{{review.title}}</p></strong>
                <p class="card-text">{{review.text}}</p>
              </div>
            </div>
            
        {%endfor%}

        {%else%}
        <h2>No reviews for this page... yet!</h2>
        {%endif%}
    </div>

    <script src="{% static 'index.js' %}"></script>

{%endblock%}